top:

  $heading: `topPage.$heading`
  $URI: `topPage.$URI`
  $sectioning:
    $specificationFileRelativePath: 01-Source/Pages/Top/TableOfContents/TopPage.toc.yaml
    $localizations:
      english: 01-Source/Pages/Top/TableOfContents/TopPage.toc.english.yaml
      japanese: 01-Source/Pages/Top/TableOfContents/TopPage.toc.japanese.yaml
      russian: 01-Source/Pages/Top/TableOfContents/TopPage.toc.russian.yaml

presets:

  $heading: `presets.$heading`

  $children:

    ESLint:

      $heading: ESLint
      $URI: `@All/Presets/ESLint/ESLintPreset.${ fileNameLocalizationExtensions }`
      $sectioning:
        $specificationFileRelativePath: 01-Source/Pages/Presets/ESLint/TableOfContents/ESLintPreset.toc.yaml
        $localizations:
          english: 01-Source/Pages/Presets/ESLint/TableOfContents/ESLintPreset.toc.english.yaml
          japanese: 01-Source/Pages/Presets/ESLint/TableOfContents/ESLintPreset.toc.japanese.yaml
          russian: 01-Source/Pages/Presets/ESLint/TableOfContents/ESLintPreset.toc.russian.yaml
