top:

  $heading: `topPage.$heading`
  $URI: `topPage.$URI`
  $sectioning:
    $specificationFileRelativePath: 01-Source/Pages/Top/TableOfContents/TopPage.toc.yaml
    $localizations:
      english: 01-Source/Pages/Top/TableOfContents/TopPage.toc.english.yaml
      japanese: 01-Source/Pages/Top/TableOfContents/TopPage.toc.japanese.yaml
      russian: 01-Source/Pages/Top/TableOfContents/TopPage.toc.russian.yaml

presets:

  $heading: `presets.$heading`

  $children:

    ESLint:

      $heading: ESLint

      $children:

        general:

          $heading: `presets.ESLint.general.$heading`
          $URI: `@All/Presets/ESLint/Common/ESLintPreset-General.${ fileNameLocalizationExtensions }`

          $sectioning:
            $specificationFileRelativePath: 01-Source/Pages/Presets/ESLint/Common/TableOfContents/ESLintPreset-General.toc.yaml
            $localizations:
              english: 01-Source/Pages/Presets/ESLint/Common/TableOfContents/ESLintPreset-General.toc.english.yaml
              japanese: 01-Source/Pages/Presets/ESLint/Common/TableOfContents/ESLintPreset-General.toc.japanese.yaml
              russian: 01-Source/Pages/Presets/ESLint/Common/TableOfContents/ESLintPreset-General.toc.russian.yaml
